- vars/slack.groovy
Add run time to Slack message, and also create a function to detect build status and printing message based on that
> Detect success/fail and add run time to the message

- vars/pipelineDockerisedVega.groovy
- vars/pipelineSystemTests.groovy
- vars/systemTests.groovy
Create dockerised-vega and system-tests pipelines and helper function run system-tests in a downstream job.
> Create dockerised-vega and system-tests pipelines

- vars/pipelineSystemTests.groovy
> Print Slack message for system-tests pipeline

- vars/pipelineDockerisedVega.groovy
Configure dockerised vega to create all the network config inside the workspace directory
Part of #6.
> Create all the network configuration inside workspace directory

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/getDockerisedVega.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
- vars/systemTests.groovy
- vars/systemTestsLNL.groovy
> Major improvements

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
- vars/slack.groovy
- vars/systemTests.groovy
- vars/systemTestsLNL.groovy
Improvements and fixes:
- you can specify commit hash or tag to clone other repos from it (the branch is still supported),
- add `ethereum-event-forwarder` to built list,
- pass `vars` variables into main stages passed to base dv pipeline,
- workaround Jenkins problem of not correctly specifying current result,
- fix the problem of building system-tests docker image and not being authenticated to GitHub pkgs,
- add an option to skip ignoring failures,
- improve how failures are ignored,
- don't hide system-tests script exit code anymore,
- introduce more message types in slack,
- more logs,
- workaround problems in a few edge cases,
> Multiple improvements

- vars/pipelineStagnetDeploy.groovy
> Update Stagnet pipeline ssh config

- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
> Set system-tests docker image name

- vars/devnetDeploy.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDevnetDeploy.groovy
- vars/slack.groovy
> Create deploy to Devnet pipelines

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDockerisedVega.groovy
> Print logs when dockerised-vega fails to start

- vars/devnetDeploy.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelinePrivateNetwork.groovy
- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
> Always stop the DV no matter what

- vars/devnetDeploy.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDevnetDeploy.groovy
> Add top up bots step to Devnet Deploy pipeline

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDockerisedVega.groovy
> Wait for bootstrap to finish in separate step

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
- vars/systemTests.groovy
- vars/systemTestsLNL.groovy
> 39 mainnet pipeline

- vars/pipelineSystemTestsLNL.groovy
> Make vegatools script available to LNL System Tests.

- vars/pipelineDockerisedVega.groovy
> Mark Stage and Build as failed when container fails

- vars/pipelineDefaults.groovy
- vars/pipelineSystemTests.groovy
https://github.com/vegaprotocol/system-tests/issues/290
> Archive test logs at the end of a run.

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDevnetDeploy.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelineStagnetDeploy.groovy
> Move to ghcr.io container registry

- vars/pipelineDockerisedVega.groovy
> Use old GH URL for backward compatibility

- vars/pipelineDockerisedVega.groovy
> Revert: withDockerRegistry does not support nesting

- vars/pipelineDockerisedVega.groovy
> Add option to discard build results older than 14 days to base pipeline

- vars/pipelineDefaults.groovy
This reverts commit 277a243612eadc33dbd15f1fd929d5444bb1cc14.
@vega-paul this fixes current develop. Will immediately open another PR to put it back in, ready for when your PR is merged.
> Revert "Update pipelineDefaults.groovy"

- vars/pipelineDefaults.groovy
This reverts commit 8b35bfd34f8a8d746cad7b8940304fd8e7077434.
@vega-paul @fkondej this will change things to work with [Paul's ](https://github.com/vegaprotocol/system-tests/pull/382) changes once those are merged. Please nobody merge until those are in. :)
> Revert "Revert "Update pipelineDefaults.groovy""

- vars/pr.groovy
- vars/withGHCLI.groovy
> Parse PR's comments and inject parameters into CI

- src/io/vegaprotocol/DockerisedVega.groovy
- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pr.groovy
- vars/systemTests.groovy
- vars/systemTestsLNL.groovy
> Remove EEF service

- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/systemTests.groovy
- vars/systemTestsLNL.groovy
Add the qa tag when building the core for qa runs.
> Add qa tag when build core for tests

- vars/devnetDeploy.groovy
> Add wait argument to devnetDeploy helper function

- vars/pipelineDefaults.groovy
- vars/pipelineDockerisedVega.groovy
- vars/pipelineMainnetCheckpointTests.groovy
- vars/pipelinePrivateNetwork.groovy
- vars/pipelineSystemTests.groovy
- vars/pipelineSystemTestsLNL.groovy
Fixes mainnet Private Network job:
Also, required for https://github.com/vegaprotocol/system-tests/pull/406
Relies on changes in:
https://github.com/vegaprotocol/system-tests/pull/406
> Mainnet checkpoint testing

- vars/pipelineDefaults.groovy
- vars/pipelineFairgroundTopUpBots.groovy
> Pipeline to top-up bots

- vars/pr.groovy
> Include review comments

- vars/pipelineApprobation.groovy
- vars/pipelineDefaults.groovy
- vars/runApprobation.groovy
> Create approbation pipeline

- vars/pipelineApprobation.groovy
Part of #96. 
Addresses https://github.com/vegaprotocol/devops-infra/issues/1275.
> Tune approbation pipeline

- vars/capsuleSystemTests.groovy
- vars/gitClone.groovy
- vars/pipelineCapsuleSystemTests.groovy
- vars/pipelineDefaults.groovy
- vars/systemTests.groovy
- vars/systemTestsCapsule.groovy
Pipeline has been tested here: https://jenkins.ops.vega.xyz/job/Experiments/job/capsule-system-tests/
Part of: https://github.com/vegaprotocol/vegacapsule/issues/18
> Add pipeline for system-tests running in the capsule

- vars/capsuleSystemTests.groovy
Closes https://github.com/vegaprotocol/vegacapsule/issues/68 
Passed pipeline: https://jenkins.ops.vega.xyz/job/system-tests/job/system-tests-capsule-experiment/3/console
> feat: improve multisig init step

- vars/capsuleSystemTests.groovy
Job for this change is running here: https://jenkins.ops.vega.xyz/job/system-tests/job/system-tests-capsule/1259/
> fix: update archive artifacts regex to **/*

- vars/capsuleSystemTests.groovy
Closes #119 
Example pipeline: https://jenkins.ops.vega.xyz/job/system-tests/job/system-tests-capsule/1535/
> feat: stop network after tests

- vars/pipelineSnapshotTesting.groovy
It does work, I tested it here:
- successful run: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2Fplaygrounds%2Fmerlin%20abc%20test/detail/merlin%20abc%20test/606/pipeline
- unsuccessful when tendermint failed: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/private%2Fplaygrounds%2Fmerlin%20abc%20test/detail/merlin%20abc%20test/602/pipeline/73
> Improve Snapshot Testing pipeline.

- vars/pipelineSnapshotTesting.groovy
Also tune the Tendermint config.toml
> Snapshot pipeline: detect more issues and print better info

- vars/capsuleSystemTests.groovy
- vars/pipelineDefaults.groovy
Pipeline: https://jenkins.ops.vega.xyz/job/common/job/system-tests/2660/
Tag created here: https://github.com/vegaprotocol/vegacapsule/releases/tag/v0.1.0
> chore: update the vegacapsule version to v0.1.0

- vars/pipelineDevnetDeploy.groovy
Now vega core sets the proper values itself
> chore: remove version setting in Devnet deploy pipeline

- vars/pipelineApprobation.groovy
> chore: archive more files for approbation

- dsl/scripts/jobs.groovy
- vars/capsulePipelineWrapper.groovy
- vars/capsuleSystemTests.groovy
- vars/pipelineSnapshotTesting.groovy
https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/Vegacapsule/job/Stagnet%203/116/console
- Adjusting pipeline for stagnet3. 
- Introducing a fix for a bug (https://github.com/vegaprotocol/vegacapsule/issues/228)
- Got rid of env variables in favor of call parameters for the capsule pipeline wrapper - testing with env variables was not very easy, and anyway, values are very stable. Moreover I feel like the env variables hidden in the job config generate confusion when you look on the pipeline code where they are coming from
> feat: update pipeline for vegacapsule network

- vars/pipelineCapsuleSystemTests.groovy
Tested smoke and nightly - both split correctly.
Test with Nightly pipeline: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-nightly/detail/system-tests-nightly/12/pipeline/36
> Update wildcards for splitting system-tests

- vars/pipelineDefaults.groovy
Updates to approbation 2.6.3 from 2.6.2
> Bump approbation

- vars/pipelineDeploy.groovy
I have tested it with pipeline: https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/Veganet/job/Devnet/308/console
> feat: provide liquidity provision commitment

- dsl/scripts/jobs.groovy
- vars/gitClone.groovy
- vars/pipelineVegavisorRestartNode.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1511
> #1511: Restart random node

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
- vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
- vars/pipelineVegavisorRestartNetwork.groovy
- vars/pipelineVegavisorRestartNode.groovy
closes https://github.com/vegaprotocol/jenkins-shared-library/issues/252
> Add locks on pipelines

- vars/pipelineVegavisorRestartNetwork.groovy
- vars/pipelineVegavisorRestartNode.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1534
> Add status sending for snapshots with elected node

- dsl/scripts/jobs.groovy
resolves vegaprotocol/devopsscripts#71
> Add code for new fairground

- dsl/scripts/jobs.groovy
- vars/pipelineVegaDevRelease.groovy
- vars/pipelineVegavisorRestartNetwork.groovy
Part of [#1532](https://github.com/vegaprotocol/devops-infra/issues/1523)
> Improve visor network restart pipeline

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
closes: https://github.com/vegaprotocol/jenkins-shared-library/issues/271
> #271: Fix paths

- vars/capsuleSystemTests.groovy
Part of https://github.com/vegaprotocol/devops-infra/issues/1521
> Pup changes

- vars/capsuleSystemTests.groovy
Triggered job: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/17483/
> feat: cleanWs on the beginning of capsuleSystemTests

- dsl/scripts/jobs.groovy
- vars/gitClone.groovy
- vars/pipelineApprobation.groovy
- vars/pipelineDefaults.groovy
- vars/runApprobation.groovy
close vegaprotocol/devops-infra#1476
> feat: Migrate existing approbation pipeline to DSL & add frontend approbation (relates to: vegaprotocol/devops-infra#1476)

- vars/pipelineVegavisorManageNode.groovy
closes vegaprotocol/devopsscripts#75
> chore: add stake step for when re-creating nodes

- dsl/scripts/jobs.groovy
Add the ` --output-csv` parameter to frontend runs
Closes #304
> chore: enable CSV output for frontend approbation

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorManageNode.groovy
relates to: https://github.com/vegaprotocol/devopsscripts/issues/75
> feat: allow to restart from remote snapshot (relates to: https://github.com/vegaprotocol/devopsscripts/issues/75)

- vars/capsuleSystemTests.groovy
Nightly & Smoke runs:
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/265/console
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/266/console
> feat: changes to make de-history testing possible: 

- dsl/scripts/jobs.groovy
closes vegaprotocol/devops-infra#1560
> chore: add regular network pipelines for Stagnet 2

- vars/capsuleSystemTests.groovy
- vars/vegautils.groovy
Close vegaprotocol/devops-infra#1552 .
https://github.com/vegaprotocol/vega/issues/6184
> feat: add protocol upgrade step

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorManageNode.groovy
- vars/vegautils.groovy
The test runs against this branch are here: 
- Validator Joining & leaving  https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/devnet1/job/Manage-Node/758/console
- Random node restart:  https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/devnet1/job/Manage-Node/760/console
After updating PR i have triggered pipelines one more time:
- https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/devnet1/job/Manage-Node/762/
- https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/devnet1/job/Manage-Node/763/
> feat: enable validator joining and leaving on the devnet1

- dsl/scripts/jobs.groovy
close vegaprotocol/devops-infra#1564
> chore: enable restarting a random node every hour from local snapshot on Devnet 1

- vars/pipelineVegavisorManageNetwork.groovy
and at the same time, it never changes
> chore: don't deploy faucet, cos it conflicts parallel task

- jcasc/jenkins.yaml
It is required before system-tests and jenkins-shared-librare are merged
- https://github.com/vegaprotocol/jenkins-shared-library/pull/334
- https://github.com/vegaprotocol/docker/pull/65
- https://github.com/vegaprotocol/system-tests/pull/1434
- https://github.com/vegaprotocol/jenkins-shared-library/pull/323
- https://github.com/vegaprotocol/ansible/pull/326
> feat: update jenkins agent to v0.2.0

- dsl/scripts/directories.groovy
- dsl/scripts/jobs.groovy
- jcasc/scripts/init.sh
- vars/pipelineSnapshotTesting.groovy
closes vegaprotocol/devops-infra#1608
> chore: migrate Stagnet 3

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
- vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
relates to: https://github.com/vegaprotocol/devops-infra/issues/1614
> feat: Configure cronjob for daily deploy to stagnet3 (relates to: https://github.com/vegaprotocol/devops-infra/issues/1614)

- vars/pipelineVegavisorManageNode.groovy
- vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
closes vegaprotocol/devops-infra#1614
> fix: pass the correct release version to ansible

- vars/pipelineCapsuleSystemTests.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1635 .
> feat: copy only required files to system tests parent job of the system-tests

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1604
> feat: Store snapshot artifacts (relates to: https://github.com/vegaprotocol/devops-infra/issues/1604)

- vars/pipelineDeployVegacapsule.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
close https://github.com/vegaprotocol/vega/issues/7212
> fix: vega wallet software version

- vars/pipelineSnapshotTesting.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1663
> feat: Implement using dehistory on jenkins pipelines (closes: https://github.com/vegaprotocol/devops-infra/issues/1663)

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorManageNode.groovy
closes: https://github.com/vegaprotocol/ansible/issues/398
> feat: Skip removing data node state by default

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1679
> feat: migrate to networkhistory from dehistory

- dsl/scripts/jobs.groovy
- vars/spamOrders.groovy
closes https://github.com/vegaprotocol/devopstools/pull/25
> feat: add spam-orders pipeline

- dsl/scripts/jobs.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1688
> feat: Do more strict rules on keeping jobs / artficats

- dsl/scripts/directories.groovy
- dsl/scripts/jobs.groovy
- vars/pipelineEthereumEvents.groovy
closes: https://github.com/vegaprotocol/jenkins-shared-library/issues/373
> feat: PoC on job for ethereum events

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleSystemTests.groovy
- vars/pipelineSnapshotSoakTest.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1701
> feat: Restore soak test pipelines logic

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1632
> Devops infra/1632

- vars/pipelineVegavisorManageNetwork.groovy
try to workaround https://github.com/vegaprotocol/devops-infra/issues/1684
> chore: increase sleep before self-delegate (for Devnet)

- dsl/scripts/jobs.groovy
Triggered builds:
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/45625/console
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/46613/console
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/46627/console
Related PRs:
- https://github.com/vegaprotocol/system-tests/pull/1753
> chore: re-enable RUN_PROTOCOL_UPGRADE_PROPOSAL_NETWORK_HISTORY

- dsl/scripts/jobs.groovy
Closes https://github.com/vegaprotocol/jenkins-shared-library/issues/387
> chore: run bots Top-Up every 6 hours for Stagnet 3

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
closes:  https://github.com/vegaprotocol/devops-infra/issues/1722
Triggered pipeline: https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Fairground/12845/console
Backuped snapshots: https://github.com/vegaprotocol/snapshot-backups/tree/main/fairground/v0.67.3/877000-877000
> feat: backup snapshots

- vars/pipelineSnapshotTesting.groovy
use information from /api/v2/snapshots as trusted block height and hash in Tendermint statesync config
> chore: use data from data-node in Tendermint statesync config

- vars/alert.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
closes vegaprotocol/jenkins-shared-library#380
> Disable alerts when restarting network or node

- dsl/scripts/jobs.groovy
> chore: disable automatic protocol upgrade for Stagnet 3

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorProtocolUpgradeNetwork.groovy
and increase the block used for Protocol Upgrade
> chore: re-enable cron for Protocol Upgrade on Stagnet 1

- dsl/scripts/jobs.groovy
and fix the path for managing node for validators testnet
> chore: move node selection to be the first parameter to select

- dsl/scripts/jobs.groovy
Triggered build: https://jenkins.ops.vega.xyz/job/common/job/visor-autoinstall-and-pup/72/
> feat: update release repo for pup and visor autoinstall tests

- dsl/scripts/jobs.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1756
> feat: add validators testnet snapshots

- dsl/scripts/jobs.groovy
closes https://github.com/vegaprotocol/ansible/issues/449
> chore: add be02 to node list

- vars/pipelineVegavisorManageNetwork.groovy
> chore: increase sleep before self-delegate after network restart

- vars/pipelineVegaMarketSim.groovy
Adds an additional stage to the nightly vega-market-sim run. Additional stage runs a fuzz test to try cause panics in core.
> feat: add fuzz test stage

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleLNL.groovy
Triggered build:
- https://jenkins.ops.vega.xyz/job/common/job/system-tests/18776/ - standard system-tests
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/264/ - LNL - failure exected
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/829/ - nightly
close vegaprotocol/devops-infra#1522
> feat: changes for extended LNL pipeline

- dsl/scripts/jobs.groovy
- vars/pipelineVegaMarketSim.groovy
PR adds archiving plots as artifacts to the fuzz tests and makes the number of steps configurable
> feat: fuzzing artifacts

- vars/pipelineVegaMarketSim.groovy
Changes param in stage to match param in job.
> fix: correct parameter typo

- resources/bin/pv-snapshot-all
- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleSystemTests.groovy
- vars/pipelineSnapshotSoakTest.groovy
There is number of run passed after I have triggered nightly system tests for this branch:
> Add debugging for snapshot soak tests

- resources/bin/pv-snapshot-all
close vegaprotocol/jenkins-shared-library#457
> Pv snapshot all forgiving

- dsl/scripts/jobs.groovy
- vars/pipelineBackupDevopsTools.groovy
Tested here: https://jenkins.ops.vega.xyz/job/private/job/playgrounds/job/DanielH/job/gitClone/169/console
> feat: the backup pipeline

- dsl/scripts/jobs.groovy
Fixes:
```
ERROR: startup failed:
jobs.groovy: 708: unexpected token: NODE_LABEL @ line 708, column 13.
NODE_LABEL: 's-4vcpu-8gb',
^
1 error
```
+ one more spotted issue
> fix: dsl file typos

- dsl/scripts/jobs.groovy
Reduces the number of iterations in the overnight vega-market-sim RL stage to reduce run time on the 16gb machine.
> feat: reduce rl iterations

- vars/capsuleSystemTests.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1841 .
- https://github.com/vegaprotocol/system-tests/pull/2070
> feat: use ignored folder to avoid the -modified binaries

- dsl/scripts/jobs.groovy
- vars/pipelineApprobation.groovy
- vars/runApprobation.groovy
Add vegawallet-browser to approbation script to pick up AC coverage metrics.
closes #480
> chore: add vegawallet-browser to approbation

- dsl/scripts/jobs.groovy
> fix: remove extra brace

- dsl/scripts/jobs.groovy
- vars/pipelineManageNode71.groovy
closes vegaprotocol/devops-infra#1866
> Create manage node 71 pipeline for mainnet

- dsl/scripts/jobs.groovy
- vars/pipelineManageNode71.groovy
- vars/pipelineVegavisorManageNode.groovy
- vars/vegautils.groovy
closes vegaprotocol/devops-infra#1865
> chore: use vega.rocks for devnet1

- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleLNL.groovy
closes https://github.com/vegaprotocol/jenkins-shared-library/issues/489 .
> feat: update slack channel for lnl mainnet notification

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleSystemTests.groovy
Reverts vegaprotocol/jenkins-shared-library#448
> Revert "feat: Archive profile files if there are any."

- vars/pipelineCapsuleLNL.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1856 .
> feat: update checkpoint source for the lnl pipeline

- vars/vegautils.groovy
Changing because first bot s exhausted by something. We will debug afer weekend
```
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 5000
x-ratelimit-remaining: 170
x-ratelimit-reset: 1684566392
x-ratelimit-used: 4830
x-ratelimit-resource: core
```
```
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4965
x-ratelimit-reset: 1684566812
x-ratelimit-used: 35
x-ratelimit-resource: core
```
> feat: use dedicated github account for jenkins pipelines

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1856 .
TBD
- https://github.com/vegaprotocol/devopsscripts/pull/92
- https://github.com/vegaprotocol/system-tests/pull/2085
- https://github.com/vegaprotocol/devopstools/pull/41
- https://github.com/vegaprotocol/jenkins-shared-library/pull/500
> feat: improve snapshot test part of the system-tests pipeline

- vars/pipelineCapsuleSystemTests.groovy
- vars/pipelineDefaults.groovy
- vars/systemTestsCapsule.groovy
- https://github.com/vegaprotocol/jenkins-shared-library/pull/523
- https://github.com/vegaprotocol/system-tests/pull/2209
> feat: pass node_label context from the system-tests repo jenkinsfile to system-tests pipeline

- vars/pipelineCapsuleLNL.groovy
- vars/vegautils.groovy
closes https://github.com/vegaprotocol/jenkins-shared-library/issues/439 .
Tested here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/509/
> feat: mainnet scenario lnl pipeline

- dsl/scripts/jobs.groovy
> chore: update browser wallet command

- dsl/scripts/jobs.groovy
- vars/pipelineCapsuleMainnetSnapshot.groovy
closes https://github.com/vegaprotocol/devops-infra/issues/1531 .
> feat: define mainnet snapshot job

- vars/pipelinePerformanceTest.groovy
- Rename variable for psql password
- Temp workaround: install psql client in the pipeline - will be removed when we are ready to roll the jenkins image out
- Do not fail when no artifacts to archive.
- https://github.com/vegaprotocol/jenkins-shared-library/pull/543
- https://github.com/vegaprotocol/performance/pull/2
> feat: improvements for the performance pipeline

- jcasc/jenkins.yaml
- vars/pipelinePerformanceTest.groovy
This reverts commit abe5e88c1cd40f6ff46e1c510edc7d7930f950c7.
> feat: add postgres client package to the agent

- dsl/scripts/jobs.groovy
- vars/capsuleSystemTests.groovy
- vars/pipelineCapsuleMainnetSnapshot.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/1531 .
Passed pipeline: https://jenkins.ops.vega.xyz/job/common/job/system-tests-mainnet-snapshot/24/console
I will be refactoring and changing this pipeline but it's a good milestone to merge I guess.
> feat: Snapshot compatibility

- vars/pipelineApprobation.groovy
> fix: browser wallet post to slack

- vars/capsuleSystemTests.groovy
close #549 .
- https://jenkins.ops.vega.xyz/job/common/job/system-tests/24150/console
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/1002/
> feat: archive data-node state

- dsl/scripts/jobs.groovy
- vars/pipelineVegaMarketSim.groovy
close vegaprotocol/devops-infra#1531 .
I had to fix the pipeline to ensure my changes to the nullchain in the Vega core wouldn't break this pipeline. 
- Added support for the following  parameters: `PARALLEL_WORKERS`, `TEST_FUNCTION`, `LOG_LEVEL`
- Fixed archiving commands
- Left comment for further improvements.
- Install the required software for the tests - The follow up issue is here (TBD)
- https://jenkins.ops.vega.xyz/job/common/job/vega-market-sim/2605/
- https://github.com/vegaprotocol/jenkins-shared-library/pull/571
- https://github.com/vegaprotocol/vega-market-sim/pull/471
> feat: improvements for vega-market-sim job

- vars/pipelineVegaMarketSim.groovy
Small fixes to fix the failing overnight run:
- build learning image stage removed
- build binaries stage added too overnight runs
- learning script migrated to script running locally
- fixed archiving fuzzing outputs
> fix: vms nightly runs

- vars/capsuleSystemTests.groovy
- vars/vegautils.groovy
close vegaprotocol/jenkins-shared-library#247 .
Triggered build: https://jenkins.ops.vega.xyz/job/common/job/system-tests/25397/
> feat: generate junit report function

- dsl/scripts/jobs.groovy
- vars/pipelineSnapshotTesting.groovy
Triggered build: https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Fairground/32458/
> feat: Update pipelineSnapshotTesting.groovy

- dsl/scripts/jobs.groovy
- vars/pipelineNetworkManageNode71.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
pipeline right after restarting node
> chore: add non-restart-required step to be executed in manage node/network

- vars/pipelineVegaMarketSim.groovy
Tested here: https://jenkins.ops.vega.xyz/job/common/job/vega-market-sim/2695/artifact/network_home/
> fix: archive artifacts in vega-market-sim

- vars/capsuleSystemTests.groovy
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/91940/pipeline
> chore: increase timeout for git clone command in capsule system tests pipeline

- dsl/scripts/jobs.groovy
- vars/pipelineNetworkManageNode71.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
> feat: add DRY_RUN option to Manage-Node, Manage-Node-71 and Manage-Network

- vars/alert.groovy
- vars/pipelineNetworkApplyNonRestartChanges.groovy
- vars/pipelineNetworkManageNode71.groovy
- vars/pipelineVegavisorManageNetwork.groovy
- vars/pipelineVegavisorManageNode.groovy
closes vegaprotocol/devops-infra#1994
> Update silencing alerts in grafana

- vars/capsuleSystemTests.groovy
- vars/vegautils.groovy
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/95323/console
> Wait for nomad

- vars/pipelineCapsuleLNL.groovy
Passed here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/636/console
> feat: use vega tools instad of vegatools

- dsl/scripts/jobs.groovy
- https://github.com/vegaprotocol/jenkins-shared-library/pull/601
- https://github.com/vegaprotocol/devopstools/pull/61
> feat: use sla-support branch of devopstools fo devnet1

- vars/pipelineSnapshotTesting.groovy
closes vegaprotocol/devops-infra#2029
> Snapshot improve

- jcasc/jenkins-new.yaml
The image has been created here: https://github.com/vegaprotocol/ansible/actions/runs/6040744360/job/16394135308
> update digital ocean jenkins ami

- vars/capsuleSystemTests.groovy
- vars/vegautils.groovy
Tested here: https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/1630/artifact/
I have manually added cron once i was able to login into server.
- https://github.com/vegaprotocol/jenkins-shared-library/pull/617
- https://github.com/vegaprotocol/ansible/pull/632
> External files archival support

- dsl/scripts/jobs.groovy
- vars/pipelineVegavisorTopupBots.groovy
Passed here: https://jenkins.vega.rocks/job/private/job/Deployments/job/devnet1/job/Topup-Bots/933/console
> feat: research bots topup support

- dsl/scripts/jobs.groovy
- vars/pipelineCleanupAgents.groovy
closes: https://github.com/vegaprotocol/devops-infra/issues/2048
> feat: draft for pipeline to cleanup agents

- vars/capsuleSystemTests.groovy
- vars/withDockerLogin.groovy
```
12:39:59  docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```
Step passed here w/o issues, however we expect other issues in the system-tests itself: https://jenkins.vega.rocks/job/common/job/system-tests-snapshot-compatibility/31/console
> feat: implement docker login logic

- jcasc/jenkins-new.yaml
Reverts vegaprotocol/jenkins-shared-library#640
> Revert "feat: disable all permanent agents"

- vars/capsuleSystemTests.groovy
- https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/7195/artifact/
> feat: list all existing images on docker machine before run

- vars/pipelineCapsuleLNL.groovy
Triggered run: https://jenkins.vega.rocks/job/common/job/system-tests-lnl-mainnet/64/console
> feat: fix lnl

- dsl/scripts/jobs.groovy
close vegaprotocol/devops-infra#2084 .
> feat: disable teams step for all envs

- vars/pipelineCleanupAgents.groovy
close vegaprotocol/devops-infra#2102 .
> feat: restart agent after cleanup process

- dsl/scripts/jobs.groovy
- vars/pipelineAnsible.groovy
close vegaprotocol/devops-infra#2102 .
> feat: add ansible playbook pipeline

- jcasc/scripts/jenkins-agent-install.sh
close vegaprotocol/devops-infra#2102 .
> feat: add modified version of jenkins-agent setup script

- dsl/scripts/jobs.groovy
- jcasc/config/all-the-rest.yaml
- jcasc/config/office-agents-manual.yaml
close vegaprotocol/devops-infra#2102 .
> feat: relabel agents for system-test kind of jobs

- .github/workflows/add_issue_to_project.yml
corrects the github token for the action adding issues to the project board
> fix: correct the GITHUB TOKEN

- vars/pipelinePerformanceTest.groovy
Add a new folder of metrics to the list of files to be archived after the pipeline has run.
Closes #729
> Add new results folder to archive list

- vars/pipelineVegaMarketSim.groovy
testing: 
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fvega-market-sim-reinforcement/detail/vega-market-sim-reinforcement/240/pipeline/152
> feat: use python unbuffered output for fuzz

- vars/pipelineSnapshotTestingNew.groovy
> feat: update snapshot-testing to include logs

- dsl/scripts/jobs.groovy
Testing here: https://jenkins.vega.rocks/job/common/job/system-tests-snapshot-compatibility/356/console
> feat: update devopstools for snapshot-compatibility pipeline

- dsl/scripts/jobs.groovy
Update config to include core unit tests.
Change tested already in https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fapprobation/detail/approbation/1754/pipeline
Closes #756
> fix(approbation): include all core unit tests

- dsl/scripts/jobs.groovy
- Update approbation to 4.9.1
- Update current milestone to `suzuka_castle`
- Update specs branch to `suzuka_castle`
- Remove unused args
Closes #758
> Update approbation for suzuka_castle

- dsl/scripts/jobs.groovy
- vars/pipelineApprobation.groovy
chore: fix current milestone branch and pass through milestone var
- **chore: bump approbation and fix specs branch**
- **fix: actually pass through current milestone**
Closes #760
> chore: update approbation to 4.9.2
