vegaprotocol/jenkins-shared-library

vars/pipelineDefaults.groovy
vars/pipelineDockerisedVega.groovy
vars/pipelineSystemTests.groovy
vars/slack.groovy
vars/systemTests.groovy

List of changes:
* decrease the default number of non-validator nodes from 2 to 1,
* fix Slack channel,
* convert some parameter types to required, e.g. integer to string, or string to bool,
* fix copying JUnit result files from a downstream job back to an upstream job.
* and more ...

Minor fixes and improvements

---

vars/pipelineDockerisedVega.groovy

All PR pipelines are running the System Tests as a downstream job run in separate pipelines: `system-tests` and `system-tests-lnl`. As part of this process: the JUnit test result files must be copied back to the upstream pipelines as part of this process. By default, it is blocked by the job permissions.
Here, we enable this permission for the dockerised-vega pipeline, a base pipeline for both the `system-tests` and the `system-tests-lnl` pipelines.

Enable copyArtifactPermission for every job

---

vars/pipelineSystemTests.groovy

Enables https://github.com/vegaprotocol/system-tests/pull/272. Change on its own should be harmless.

Pass the location of the vegatools script to the system tests.

---

vars/pipelineStagnetDeploy.groovy

We do not have known_hosts when new jenkins runner is starting

Disable checking known hosts for ansible

---

vars/pipelineDefaults.groovy

- Update to `v2.4.1`
- Update `ignore` param to ignore Wendy spec
- Update extra params to show verbose output

Update default configuration for approbation pipe

---

src/io/vegaprotocol/DockerisedVega.groovy
vars/pipelineDefaults.groovy
vars/pipelineDockerisedVega.groovy
vars/pipelineMainnetCheckpointTests.groovy
vars/pipelinePrivateNetwork.groovy

This should have the effect of:
- Regular LNL tests resume the network after checkpoints as they do currently (the new behaviour)
- Mainnet pipeline should pass the "--legacy-resume" flag to DV, which ought to trigger the old behaviour.
- We can flip/remove later, once mainnet is on a more recent version.

fix: Make mainnet pipeline trigger the legacy checkpoint behaviour

---

vars/gitClone.groovy

Part of #95 
Tested here: https://jenkins.ops.vega.xyz/job/Experiments/job/gitClone/11/console
With the following code:
```
@Library('vega-shared-library@git-clone') _
node('system-tests-capsule') {
stage('test') {
gitClone([
credentialsId: 'vega-ci-bot',
url: 'git@github.com:vegaprotocol/vegacapsule.git',
branch: 'main'
])
gitClone([
credentialsId: 'vega-ci-bot',
url: 'git@github.com:vegaprotocol/vegacapsule.git',
branch: 'main',
directory: 'abc'
])
gitClone([
credentialsId: 'vega-ci-bot',
branch: 'main',
directory: 'def'
])
sh 'pwd'
sh 'ls -als'
dir('abc') {
sh 'pwd'
sh 'ls -als'
}
dir('def') {
sh 'pwd'
sh 'ls -als'
}
}
}
```

Add git clone helper

---

vars/pipelineApprobation.groovy
vars/pipelineDefaults.groovy

Done so far:
- Bump version
- Fix incorrect `--verbose` argument
- Add `output-jenkins`
- add `output-csv`
Please could someone from Ops complete these last two tasks:

Update approbation default config & minor pipeline changes

---

vars/pipelineDockerisedVega.groovy

Tested here: https://jenkins.ops.vega.xyz/job/private/job/LNL-create-restore/7035/
`dockerisedvega.stop()` without the `resume` removes containers, so we have to print logs before it.
```
[2022-06-07T17:49:00.872Z] Stopping and removing container(s): dv-LNL-create-restore-7035-1-vega-faucet*
[2022-06-07T17:49:01.134Z] 1dfc776b380b
[2022-06-07T17:49:01.440Z] 1dfc776b380b
[2022-06-07T17:49:01.440Z] Stopping and removing container(s): dv-LNL-create-restore-7035-1-vega-wallet*
[2022-06-07T17:49:01.740Z] 59ebfd8d87cb
[2022-06-07T17:49:02.046Z] 59ebfd8d87cb
[2022-06-07T17:49:02.046Z] Stopping and removing container(s): dv-LNL-create-restore-7035-1-data-node*
[2022-06-07T17:49:02.713Z] 019a307ffb43
[2022-06-07T17:49:02.977Z] 019a307ffb43
[2022-06-07T17:49:02.977Z] Stopping and removing …
```

fix: Print logs when network is failed before docker containers are removed

---

vars/capsuleSystemTests.groovy
vars/pipelineCapsuleSystemTests.groovy
vars/pipelineDefaults.groovy
vars/systemTestsCapsule.groovy

closes #131 
we also now pass in a nomad config to overwrite the default resource caps (and also it kinda makes sense for the system tests repo to be able to control this config)

feat: make the vega capsule config a build parameter

---

vars/pipelineApprobation.groovy
vars/pipelineDefaults.groovy

- Update pipelineApprobation.groovy to rename variables
- Update pipelineDefaults to use new variables & default to specs
vegaprotocol/specs-internal is being made public, replacing the old
vegaprotocol/specs repo. The latter was just a mirror of the former with
some files filtered out - we no longer feel it is required, so we're
just replacing one with the other. This PR updates the variable names
and defaults related to the repo that approbation runs against.

Make approbation to run against vegaprotocol/specs

---

vars/capsulePipelineWrapper.groovy

- Wrapped paths in slashes(`'`), which are required if the working directory in Jenkins contains space.
- Moved `sync local to remote` step, because we need to sync at very end of the pipeline when all steps are finished.
Passed pipeline: https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/Vegacapsule/job/Stagnet%203/16/console
Failed pipelines: All pipelines before 15:  https://jenkins.ops.vega.xyz/job/private/job/Deployments/job/Vegacapsule/job/Stagnet%203/

Fix some small mistakes in stagnet3 pipeline

---

vars/capsulePipelineWrapper.groovy

- I have updated the procedure of building binaries from the cloned repository
- Fixed a small typo in the devnet2 pipeline
- Now cloning vega(for vega and data-node) is not parallel to avoid:
- Conflict when we use the same version
- Cloning the same repo versions to different folders

fix: fix issues for cloning vega core and build binaries

---

vars/pipelineDefaults.groovy

Now that https://github.com/vegaprotocol/approbation/pull/53 has been merged I will create a new tag and then request that this is reviewed and merged in order to get the latest priorities updated
Needs to wait until: https://github.com/vegaprotocol/approbation/pull/55 is merged and the 2.6.5 tag is created.

chore: update approbation version

---

dsl/scripts/jobs.groovy
vars/pipelineDeploy.groovy

Pipeline is failing when it's triggered manually on branch different than development. For example on the PR.

fix devnet deployment pipeline

---

vars/pipelineDefaults.groovy

Bumps version for the changes required in:
resolves vegaprotocol/specs#1282
DO NOT MEREGE UNTIL THIS HAS BEEN:
- https://github.com/vegaprotocol/approbation/pull/58
and a new tag for 2.7.1 has been created in https://github.com/vegaprotocol/approbation

chore: bump approbation version

---

dsl/scripts/jobs.groovy
vars/pipelineApprobation.groovy

Approbation 4.0.0 (https://www.npmjs.com/package/@vegaprotocol/approbation/v/4.0.0) adds a new parameter (`--categories`) that is required, and points to a `.json` file in the spec repo. This PR bumps the required version of approbation, and also adds the new parameter, tailored to whether it is core or frontend
- Update approbation version
- Add new stringParam `categories`
- Update pipeline to pass in new param
Closes #296

Update approbation to 4.0.0, add new parameter

---

dsl/scripts/jobs.groovy

Current default configuration for frontend approbation misses some test references as they are in `.cy.ts` files. This PR expands the globs a bit.
- Update test glob to include `.ts`, `.tsx`, `.jsx` as well as `.js`
Closes #299

chore: expand frontend approbation test globs

---

vars/capsuleSystemTests.groovy

Part of https://github.com/vegaprotocol/devops-infra/issues/1570
Changes:
- Start nomad as root
- Do not stop partially failed network when there is an error to make debugging easy

feat: system-tests  do not stop network on start failure

---

vars/capsuleSystemTests.groovy

Reverts vegaprotocol/jenkins-shared-library#307
needs debugging why it is failing here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/19743/console

Revert "feat: system-tests  do not stop network on start failure"

---

vars/capsuleSystemTests.groovy

Archiving of the state for data node is skipped: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/20733/artifact/testnet/data/

feat: exclude vega socket and de-history files from archive

---

vars/pipelineSnapshotTesting.groovy

we already have `pex=true`, and set `seeds`, so we don't need to set `persistent_peers`

chore: Snapshot pipeline: use seeds and remove malformed entries

---

vars/pipelineCapsuleSystemTests.groovy

We do not need to call `cleanWs()` because there is nothing to clean after this pipeline. It cleans the workspace on the jenkins agent but here we do not have any jenkins agent, so no trashes are produced
Triggered build: https://jenkins.ops.vega.xyz/job/common/job/system-tests/13186/console

fix: fix the post-always-action

---

dsl/scripts/jobs.groovy
vars/capsuleSystemTests.groovy
vars/pipelineDefaults.groovy

We are removing support for docker in the system-tests. We want to adjust pipeline to execute pretty much the same steps as QA developers executes locally
- https://github.com/vegaprotocol/docker/pull/65
- https://github.com/vegaprotocol/system-tests/pull/1434
- https://github.com/vegaprotocol/jenkins-shared-library/pull/323
- https://github.com/vegaprotocol/ansible/pull/326
- https://github.com/vegaprotocol/jenkins-shared-library/pull/334

feat: remove system-tests docker

---

dsl/scripts/jobs.groovy

I just updated the parameter where the version number was to be latest. Reason:
1. We may want to revert back to using a specific version quickly
2. we could remove the param and add `latest` into [here](https://github.com/vegaprotocol/jenkins-shared-library/blob/9be4eeeed91082767e8208056a1d5829f0cd3894/vars/pipelineApprobation.groovy#L134) but that seemed final and I was not sure of any consequences of doing this without me having some local way of testing.
cc @edd

chore: make approbation always run on latest

---

vars/pipelineCapsuleLNL.groovy

closes https://github.com/vegaprotocol/devops-infra/issues/1645 .
The triggered run is here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/122/console
It failed in the test stage, but it passed download checkpoint stage. The failure will be fixed in other PR.

feat: use new mainnet api servers for the checkpoint source in the lnl mainnet pipeline

---

dsl/scripts/jobs.groovy
vars/pipelineApprobation.groovy

In order to cover the spec ACs in [0071-STAK-erc20_governance_token_staking.md](https://github.com/vegaprotocol/specs/blob/master/protocol/0071-STAK-erc20_governance_token_staking.md)
This [system test issue](https://github.com/vegaprotocol/system-tests/issues/729) was created. A number of the tests have been written in truffle and in the smart contract repos:
- https://github.com/vegaprotocol/Vega_Token_V2/pull/14
- https://github.com/vegaprotocol/Staking_Bridge/pull/9
These ACs have been tagged in the tests in the above repo code, however, are not showing in the [coverage report](https://jenkins.ops.vega.xyz/blue/rest/organizations/jenkins/pipelines/common/pipelines/approbation/runs/1809/nodes/128/steps/129/log/?start=0)
@edd / @vegaprotocol/ops I have left this PR as a draft as I'm not …

chore: add smart contract repos to approbation

---

jcasc/jenkins.yaml

We need new ami because the old one has no account role applied which disallow users to ssh into the boxes

feat: bump jenkins ami to v0.3.1

---

vars/pipelineApprobation.groovy

The branch params allow the passing of commit hash and tags, not only branch names

fix: approbation git clone

---

vars/capsuleSystemTests.groovy

Initially exactly the same change has been implemented for visor pup automatic download test. 
Triggered pipelines:
- https://jenkins.ops.vega.xyz/job/private/job/playgrounds/job/pup-testing/48/  - visor pup automatic download - passed
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/714/ - nightly
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/ - some subset of system-tests

feat: do not archive vega binaries after system-tests

---

vars/pipelineVegavisorProtocolUpgradeNetwork.groovy

closes vegaprotocol/devops-infra#1726

chore: don't wait for vegawallet in Protocol Upgrade pipeline

---

dsl/scripts/jobs.groovy

Disable it temporarily, cos this step always fails. We can re-enable it once we find and fix the issue.

chore: disable backing up snapshots for Fairground network

---

dsl/scripts/jobs.groovy
vars/pipelineApprobation.groovy

Switches from using NPM as the source of approbation to Github, without a version spec as we always use latest
- Update `Run Approbation` stage
This was something we had planned to do for a while, but was triggered when 4.3.4 was tagged with a tag that didn't match the expected format, causing 4.3.4 not to be published to npm, leading to confusion as to why it wasn't running the latest code.
Closes #414

build(approbation): use latest from github always

---

dsl/scripts/jobs.groovy
vars/pipelineApprobation.groovy

Frontend has two different perspectives for AC coverage, categories and apps
This PR adds a second approbation run for frontend only that takes a new parameter
One potential problem could be that it would overwrite test results. I haven't dealt with that
- Add new paramter
- Add new stage that only runs for frontend
Closes #420
Whoever reviews this - if I have made a terrible error, @pennyandrews knows what I am trying to achieve if I am unavailble.

build(frontend): configure a second approbation run for frontend

---

dsl/scripts/jobs.groovy

the lock can be disabled with the `DISABLE_LOCK` parameter

chore: enable concurrent builds for Manage-Node, as we have lock

---

dsl/scripts/jobs.groovy

closes vegaprotocol/devops-infra#1821

chore: disable top up for extra bots on Stagnet 1

---

dsl/scripts/jobs.groovy

Noticed that I am missing a job for vegawallet browser. This could be what is causing the approbation failures.
closes #487

fix: add vegawallet-browser job

---

dsl/scripts/jobs.groovy
vars/pipelineNetworkApplyNonRestartChanges.groovy

closes vegaprotocol/jenkins-shared-library#495

chore: add non-restart-required pipeline for Mainnet using different playbook

---

dsl/scripts/jobs.groovy
vars/capsuleSystemTests.groovy

Changes:
- Change the machine to DO, because AWS machines are burstable and it causes many issues when there is no CPU credit for the machine that runs the LNL pipeline.
- We increased the number of block to use for protocol upgrade. It is required because sometimes data-node is behind and reports not the latest block

feat: increase block upgrade for system-tests proposal

---

dsl/scripts/jobs.groovy

In order to make the approbation pipeline point at the `cosmicelevator` branch in the specs repo this PR changes the branch its looking at.
This will allow us to track AC coverage on the cosmicelevator branch during the development/testing of this . 
There is a periodic (manual) task to keep the cosmic elevator branch up-to-date with master which will mean that any changes for Alpha Mainnet specs/ACs will (with a slight lag) get updated and be present in the approbation run.

chore: point approbation at cosmicelevator branch

---

dsl/scripts/jobs.groovy
vars/pipelineVegaMarketSim.groovy
vars/vegaMarketSim.groovy

vega-market-sim tests (which will be added by vegaprotocol/vega-market-sim#411) require `vegacapsule` available on the host. PR adds a stage for cloning `vegacapsule`.

feat: clone capsule in vega-market-sim job

---

jcasc/jenkins.yaml

I have built image for testing manually from this branch: https://github.com/vegaprotocol/ansible/pull/582
```
==> Wait completed after 59 minutes 248 milliseconds
==> Builds finished. The artifacts of successful builds are:
--> digitalocean.this: A snapshot was created: 'jenkins-agent-v0-5-0-pre1' (ID: 135114985) in regions 'fra1'
--> digitalocean.this: A snapshot was created: 'jenkins-agent-v0-5-0-pre1' (ID: 135114985) in regions 'fra1'
```

feat: add new do instance with python 3-11 for jenkins

---

jcasc/jenkins.yaml

Added python 3.8 nodes with the following labels:
- `g-8vcpu-32gb-python-3.8`, `generic-8vcpu-32gb-python-3.8`
- `s-8vcpu-16gb-python-3.8`, `generic-8vcpu-16gb-python-3.8`
- `s-4vcpu-8gb-python-3.8`, `generic-4vcpu-8gb-python-3.8`

feat: add jenkins nodes with python 3.8

---

dsl/scripts/jobs.groovy
vars/pipelineApprobation.groovy
vars/runApprobation.groovy

Decouple browser wallet from the frontend approbation checks.
closes #551

chore: decouple browser wallet

---

resources/bin/snapshot-soak-test

The script was previously only printing information about consensus fails to the screen, but snapshots can also fail _during_ the process of starting, so we now print the stderr to the screen whenever a failing occurs.
full-run:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests/detail/system-tests/24371/pipeline/40

Even better snapshot soak script

---

vars/pipelineCapsuleSnapshotCompatibility.groovy

closes https://github.com/vegaprotocol/devops-infra/issues/1531 .
Snapshot compatibility: https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility/15/

feat: adjust snapshot-compatibility pipeline code

---

vars/capsuleSystemTests.groovy

- Protocol upgrade + snapshot check with @ze97286 's script will be executed even when system tests fail
- SOAK test will run even after system-tests failure
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/86579/

feat: change default value for fastFail to false in the system-tests

---

vars/capsuleSystemTests.groovy

There was an issue that the build status was set to `FAULURE` but all stages were green. See the screen below for this job: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/86804/pipeline/511
After the change We can see correct results: 
- Passed results: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/86818/console
- Failed ste & Stage: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/86865/console ( see screen below)

feat: improve fast fail logic

---

vars/capsuleSystemTests.groovy
vars/pipelineCapsuleSnapshotCompatibility.groovy

- Disabled SOAK test for snapshot compatibility
- Disable network protocol upgrade test for snapshot compatibility
- https://github.com/vegaprotocol/vega/pull/8887
- https://github.com/vegaprotocol/jenkins-shared-library/pull/568
- https://github.com/vegaprotocol/devopstools/pull/53
- https://github.com/vegaprotocol/system-tests/pull/2323
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility/46/
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility/45
- https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility/43

feat: add steps for debugging snapshot compatibility

---

vars/pipelineSnapshotTesting.groovy

Some fixes for my previous changes that caused mainnet pipeline to fail
- Mainnet job: https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Mainnet/5248/
- Fairground: https://jenkins.ops.vega.xyz/job/private/job/Snapshots/job/Fairground/32464

feat: fix the remoteServerCometBFT url

---

dsl/scripts/jobs.groovy

closes vegaprotocol/devops-infra#2008

chore: change cron zfs backups to be done on api0

---

vars/pipelineCleanupAgents.groovy

- Add more docker images to the cache 
- Fix the docker cleanup steps
- Filter only online computers - ignore offline which stops the job to finish
- Add retry&timeouts to particular steps
- Reorder steps
- Move `cleanWs` into the agent, - we cannot run it in the pipeline because there is no node
- https://jenkins.vega.rocks/job/private/job/agents-cleanup/27/ - multiple nodes - failed for the jenkins25, fixed and rerun later(see next link)
- https://jenkins.vega.rocks/job/private/job/agents-cleanup/35/console - single node

feat: fixes&improvements for cleanup-agents

---

resources/grafana-agent-basic.yaml

- https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/15600/consoleFull
- https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/15630/consoleFull
With that collector i was able to collect memory usage for ganache/postgresql and the CPU usage for network nodes and components like ganache/clef/postgresql
You can check dashboard here:  https://monitoring.vega.community/d/b0d2f7c2-cf92-4487-8349-1f4d30d45e8e/system-tests?orgId=1&var-agent=jenkins-fra1-ubuntu-aaf23212-a723-409a-a936-31ecb85de81f&from=1695808390955&to=1695810315406

feat: add nomad metrics for exporter

---

dsl/scripts/jobs.groovy
vars/pipelineCapsuleSnapshotCompatibility.groovy

- https://github.com/vegaprotocol/jenkins-shared-library/pull/690
- https://github.com/vegaprotocol/devopstools/pull/82
- https://github.com/vegaprotocol/system-tests/pull/2839

feat: use new commands from devopstools for snapshot-compatibility pipeline

---

vars/pipelineCapsuleSnapshotCompatibility.groovy

Alert is properly sent to #snapshot-notify:
Here is a run I triggered: https://jenkins.vega.rocks/job/common/job/system-tests-snapshot-compatibility/112/

feat: change channel for mainnet snapshot compatibility notifications

---

vars/pipelineSnapshotTesting.groovy
vars/vegautils.groovy

- Added some debugging info, it helps see the failure reason when some of the peers are not ready
- Improving mechanism for RPC_PEER address collection - important in mainnet because not everyone opens the 26657 port from the tendermint, so we have to use our own servers to sync.
- We increase the counter when data-node is not healthy. Sometimes there is just one hiccup usually when the data-node produces snapshots. When the data-node is healthy again I decrease those penalties counter.

feat: improvement for the snapshot testing pipeline

---

dsl/scripts/jobs.groovy

In order to make the approbation pipeline point at the cosmicelevator branch in the specs repo this PR changes the branch its looking at.
This will allow us to track AC coverage on the palazzo branch during the development/testing of this .
There is a periodic (manual) task to keep the palazzo branch up-to-date with master which will mean that any changes for Palazzo specs/ACs will (with a slight lag) get updated and be present in the approbation run.

chore: point approbation at palazzo branch

---

dsl/scripts/jobs.groovy

This updates the version of approbation used as default by Jenkins

chore: Update jobs.groovy to have the correct default approbation version

---

dsl/scripts/jobs.groovy
vars/pipelineBackupNodeZFS.groovy
vars/slack.groovy

close vegaprotocol/devops-infra#2095 .
- Incrase mainnet backup timeline to 8h.
- Create mainnet backup every 24h instead of every 6h.
- Send messages to #ops-alerts for the backup pipeline

feat: increase mainnet backup timeout to 8h

---

dsl/scripts/jobs.groovy

Updates the version of approbation on to 4.6.2 to get the updates from:
- https://github.com/vegaprotocol/approbation/pull/130

chore: updates version of approbation to the latest

---

dsl/scripts/jobs.groovy

This PR updates the directories that approbation checks for AC codes.
Adds the path:
`/workspace/vega/commands/**/*.{go,feature}`

chore: check core unit tests for AC coverage

---

dsl/scripts/jobs.groovy

This points the approbation run at the colosseo branch for the new milestone

chore: point approbation at colosseo

---

vars/pipelineCapsuleSystemTests.groovy

closes https://github.com/vegaprotocol/system-tests/issues/3468
Jenkins run down to 3hr11mins:
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests/detail/system-tests/10490/pipeline
Failures all look like our familiar friends, except for the soak-test which is failing on the event file diff check. I'll look into that but I think its worth merging this anyway so we can get the benefit of the overnight runs over the weekend.

feat: remove fuzz and split o-r

---

dsl/scripts/jobs.groovy

PR adds a job run overnight to run the market-sim fuzzing tests specifically against the mainnet tag.

feat: add job for fuzzing overnight against mainnet tag

---

dsl/scripts/jobs.groovy
vars/pipelineVegaMarketSim.groovy

Removes the reinforcement learning tests from the market-sim overnight runs.

chore: disable overnight RL tests

---

vars/pipelineVegaMarketSim.groovy

Overnight market sim runs currently failing as the legacy fuzz test puts a large load on data node and eventually times out making requests.
The updated "sensible" fuzz testing as been passing (and finding new panics) in overnight runs for enough time now to deprecate the legacy fuzzing and enable only the new fuzzing.
PR also does some housekeeping removing the old plot test stage as this has largely been replaced by vegapy.

chore: disable deprecated market-sim stages

---

vars/pipelineVegaMarketSim.groovy

... as per slack request, adds the vega version to the overnight run message posted to `#vega-market-sim-notify` each night.

feat: add vega version to slack message
